// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAS1CksKMoe_A5HDrg--kHFvTLIEbhH27Q',
    appId: '1:1020157730762:web:fee5c2fb34f4a2c939f933',
    messagingSenderId: '1020157730762',
    projectId: 'money-detection-ad243',
    authDomain: 'money-detection-ad243.firebaseapp.com',
    storageBucket: 'money-detection-ad243.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDJt8ZI02O2ndXTrhldrIwjTB0xAMJDeVg',
    appId: '1:1020157730762:android:df6301ad339f318639f933',
    messagingSenderId: '1020157730762',
    projectId: 'money-detection-ad243',
    storageBucket: 'money-detection-ad243.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDEyHOIDHwvOvUtOTh10b3WuY9_J4N7Xmc',
    appId: '1:1020157730762:ios:3508421b70e0fee139f933',
    messagingSenderId: '1020157730762',
    projectId: 'money-detection-ad243',
    storageBucket: 'money-detection-ad243.appspot.com',
    iosBundleId: 'com.example.gpProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDEyHOIDHwvOvUtOTh10b3WuY9_J4N7Xmc',
    appId: '1:1020157730762:ios:4e09abe8541a50ce39f933',
    messagingSenderId: '1020157730762',
    projectId: 'money-detection-ad243',
    storageBucket: 'money-detection-ad243.appspot.com',
    iosBundleId: 'com.example.gpProject.RunnerTests',
  );
}
